CI: verify that Python requirements have been compiled (#3690)

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -79,6 +79,15 @@ jobs:
       - name: Verify missing migrations
         run: python manage.py makemigrations --check
 
+      # Confirm that requirements have been correctly compiled
+      - name: Check compiled requirements
+        run: |
+          bash docker/compile_requirements.sh
+          if ! git diff --quiet --exit-code requirements/; then
+            echo "Error: The requirements files are not up to date. Please run 'bash docker/compile_requirements.sh' and commit the changes."
+            exit 1
+          fi
+
       - name: Run tests
         run: pytest --cov-report=xml:pontoon/coverage.xml --cov=.
       - uses: codecov/codecov-action@v4
